parameters:

services:
  _defaults:
    autowire: true
    autoconfigure: true

  L00ly\MediaBundle\Controller\MediaController: ~
  L00ly\MediaBundle\Controller\ApiController: ~

  L00ly\MediaBundle\Repository\MediaRepositoryInterface:
    class: L00ly\MediaBundle\Repository\MediaRepository

  L00ly\MediaBundle\Utilities\FileUploaderInterface:
    class: L00ly\MediaBundle\Utilities\FileUploader

  L00ly\MediaBundle\Service\MediaServiceInterface:
    class: L00ly\MediaBundle\Service\MediaService

  L00ly\MediaBundle\Twig\MediaExtension: ~