parameters:

services:
  _defaults:
    autowire: true
    autoconfigure: true

  Looly\Media\Controller\MediaController: ~
  Looly\Media\Controller\ApiController: ~

  Looly\Media\Repository\MediaRepositoryInterface:
    class: Looly\Media\Repository\MediaRepository

  Looly\Media\Utilities\FileUploaderInterface:
    class: Looly\Media\Utilities\FileUploader

  Looly\Media\Service\MediaServiceInterface:
    class: Looly\Media\Service\MediaService

  Looly\Media\Twig\MediaExtension: ~